controller_params:
  num_links: 2
  links: [
    {
      length: 0.85,
      base_point: [-0.171, -0.187],
      exclusion_radius: 0.15,
      motor_radius: 0.025,
      tendon_radius: 0.011,
      gear_ratio: 64
    },
    {
      length: 0.85,
      base_point: [0.662, -0.187],
      exclusion_radius: 0.15,
      motor_radius: 0.025,
      tendon_radius: 0.011,
      gear_ratio: 64
    },
  ]
  bounds: [[0, 0.45], [0, 0.45]]
trajectory_params: 
  v_max: 9
  a_max: 25
  d_max: 25